# SPDX-License-Identifier: GPL-2.0
#
# Generic Hardware Spinlock framework
#

obj-$(CONFIG_HWSPINLOCK)		+= hwspinlock_core.o
obj-$(CONFIG_HWSPINLOCK_OMAP)		+= omap_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_QCOM)		+= qcom_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_SIRF)		+= sirf_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_SPRD)		+= sprd_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_STM32)		+= stm32_hwspinlock.o
obj-$(CONFIG_HSEM_U8500)		+= u8500_hsem.o
obj-$(CONFIG_HWSPINLOCK_MT5870)		+= mt5870_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_MT5896)		+= mt5896_hwspinlock.o
