/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#define CLK_TOPGEN_FCIE_CK	0
#define CLK_TOPGEN_FCIE_SYN_CK	1
#define CLK_TOPGEN_IMI_CK	2
#define CLK_TOPGEN_NJPD_CK	3
#define CLK_TOPGEN_LZMA_CK	4
#define CLK_TOPGEN_XTAL_12M_CK	5
#define CLK_TOPGEN_XTAL_24M_CK	6
#define CLK_TOPGEN_SMI_CK	7
#define CLK_TOPGEN_PARSER_CK	8
#define CLK_TOPGEN_TSP_CK	9

#define	CLK_TOPGEN_FAKE_NUM	1001
#define CLK_TOPGEN_AIA_MDLA_CK	CLK_TOPGEN_FAKE_NUM
#define	CLK_TOPGEN_UFS_CK	CLK_TOPGEN_FAKE_NUM
#define CLK_TOPGEN_UFS_UNIPRO_CG_SYN_CK	CLK_TOPGEN_FAKE_NUM
#define CLK_TOPGEN_UFS_AES_CK	CLK_TOPGEN_FAKE_NUM
#define CLK_TOPGEN_PEXTP_TL_CLK_CK	CLK_TOPGEN_FAKE_NUM
#define	CLK_TOPGEN_VDEC_LAE_SLOW_CK	CLK_TOPGEN_FAKE_NUM
#define	CLK_TOPGEN_VDEC_SYS_CK		CLK_TOPGEN_FAKE_NUM
#define	CLK_TOPGEN_VDEC_SYS_SLOW_CK	CLK_TOPGEN_FAKE_NUM
#define	CLK_TOPGEN_VENC_CK	CLK_TOPGEN_FAKE_NUM
#define	CLK_TOPGEN_AESDMA_CK	CLK_TOPGEN_FAKE_NUM
#define CLK_TOPGEN_ECC_CK	CLK_TOPGEN_FAKE_NUM
