/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#define CLK_USB_NONPM_EN_MCU_NONPM2SSUSB	1
#define CLK_USB_NONPM_EN_SMI2SSUSB	2
#define CLK_USB_NONPM_EN_SSUSB_SYS2SSUSB	3
#define CLK_USB_NONPM_EN_SSUSB_XHCI2SSUSB	4
#define CLK_USB_NONPM_EN_SSUSB_FRMCNT2SSUSB	5
#define CLK_USB_NONPM_EN_XTAL_24M2TSP_MBIST	6
#define CLK_USB_NONPM_EN_SSUSB_PCLK2SSUSB	7
#define CLK_USB_NONPM_EN_SSUSB_PCLK_1P2SSUSB	8
#define CLK_USB_NONPM_EN_SSUSB_USB20_PHY_CLK2SSUSB	9
#define CLK_USB_NONPM_EN_SSUSB_USB20_PHY_CLK_1P2SSUSB	10
#define CLK_USB_NONPM_EN_SSUSB_USB20_PHY_CLK_2P2SSUSB	11
#define CLK_USB_NONPM_EN_IMI2SHARE_SRAM_IMI	12
#define CLK_USB_NONPM_EN_MCU_NONPM2USB20	13
#define CLK_USB_NONPM_EN_SMI_UHC2UHC	14
#define CLK_USB_NONPM_EN_USBPHY2402USB20_SHBG	15
#define CLK_USB_NONPM_EN_USBPHY240_MUX2USB20_SHBG	16
#define CLK_USB_NONPM_EN_USBPHY302USB20_SHBG	17
#define CLK_USB_NONPM_EN_MCU_NONPM2PEXTP	18
#define CLK_USB_NONPM_EN_PEXTP_AHB_APB2PEXTP	19
#define CLK_USB_NONPM_EN_PEXTP_PL_PCLK2PEXTP	20
#define CLK_USB_NONPM_EN_PEXTP_TL2PEXTP	21
#define CLK_USB_NONPM_EN_SMI2PEXTP	22
#define CLK_USB_NONPM_EN_XTAL_24M2PEXTP	23
#define CLK_USB_NONPM_EN_MCU_NONPM2SSUSB_DIG_PHY_TOP	24
#define CLK_USB_NONPM_EN_XTAL_12M2SSUSB_DIG_PHY_TOP	25
#define CLK_USB_NONPM_EN_MCU_NONPM2SSUSB_DIG_PHY_TOP_P1	26
#define CLK_USB_NONPM_EN_XTAL_12M2SSUSB_DIG_PHY_TOP_P1	27
#define CLK_USB_NONPM_EN_MCU_NONPM2SSUSB_U2_PHY_TOP	28
#define CLK_USB_NONPM_EN_XTAL_12M2SSUSB_U2_PHY_TOP	29
