# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CRYPTO_DEV_MEDIATEK_DTV) += mtk-dtv-crypto.o
mtk-dtv-crypto-objs:= mtk-dtv-platform.o mtk-cipher.o

ccflags-y += -I$(srctree)/drivers/iommu/mtk_iommu_dtv
