# SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause)

ccflags-y      +=  -I$(srctree)/mm

obj-$(CONFIG_MTK_MEMORY) = mtk-memory.o
mtk-memory-objs = mtk-reserved-memory.o mtk-cma.o
mtk-memory-objs += mtk-null-memory.o
