# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cmdq/mailbox
obj-$(CONFIG_MTK_CMDQ) += mtk-cmdq-helper.o
obj-$(CONFIG_MTK_DVFSRC) += mtk-dvfsrc.o mtk-dvfsrc-start.o
obj-$(CONFIG_MTK_IPI) += mtk_tinysys_ipi.o
obj-$(CONFIG_MTK_MBOX) += mtk-mbox.o
obj-$(CONFIG_MTK_PMIC_WRAP) += mtk-pmic-wrap.o
obj-$(CONFIG_MTK_SCPSYS) += mtk-scpsys.o
obj-$(CONFIG_MTK_DEVAPC) += devapc/
obj-$(CONFIG_MTK_DEVMPU) += devmpu/
obj-$(CONFIG_MTK_MMDVFS) += mtk-mmdvfs.o
obj-$(CONFIG_MTK_MZCCMDQ_HW) += mzc/
obj-$(CONFIG_MTK_ZDEC) += zdec/
obj-$(CONFIG_MTK_PM) += mtk-pm.o
obj-$(CONFIG_MTK_BOOTTIME) += mtk-boottime.o
# TODO Remove this after garbage is taken out
obj-y += realtime/
obj-$(CONFIG_TEE) += mtk-boot/
obj-$(CONFIG_TEE) += tv_tee/
obj-$(CONFIG_MTK_MEMORY) += mtk-memory/
obj-$(CONFIG_MTK_BDMA) += mtk-bdma/
obj-$(CONFIG_MTKTV_WS_TSF) += mtk_ws_tsf/
