/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef _HAL_PCMCIA_DIFF_H_
#define _HAL_PCMCIA_DIFF_H_

#define PCMCIA_PE_CTRL_SUPPORTED     0
#define PCMCIA_OPTION_CONFIG_SUPPORTED     1
#define PCMCIA_CD1_OR_CD2_SUPPORTED     1
#define PCMCIA_PCM1_CE_LOW_SUPPORTED     1
#define PCMCIA_PCM2_CE_LOW_SUPPORTED     1
#define PCMCIA_PCM1_RESET_IN_SUPPORTED     1
#define PCMCIA_PCM2_RESET_IN_SUPPORTED     1
#define PCMCIA_MSPI_SUPPORTED     1
#define PCMCIA_CHECKMANDATORY_SUPPORTED     1
#define PCMCIA_SETPADMUX_SUPPORTED     0
#define PCMCIA_MSPI_BURST 0
#endif
