##############################################################################
#MediaTek Inc. (C) 2018. All rights reserved.
#Copyright Statement:
#This software/firmware and related documentation ("MediaTek Software") are
#protected under relevant copyright laws. The information contained herein is
#confidential and proprietary to MediaTek Inc. and/or its licensors. Without
#the prior written permission of MediaTek inc. and/or its licensors, any
#reproduction, modification, use or disclosure of MediaTek Software, and
#information contained herein, in whole or in part, shall be strictly
#prohibited.
#BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
#THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
#RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
#ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
#WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
#WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
#NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
#RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
#INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
#TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
#RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
#OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
#SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
#RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
#STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
#ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
#RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
#MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
#CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#The following software/firmware and/or related documentation ("MediaTek
#Software") have been modified by MediaTek Inc. All revisions are subject to
#any receiver's applicable license agreements with MediaTek Inc.
##############################################################################
LOCAL_PATH ?= $(M)

export CONFIG_DRM_MEDIATEK_TV=m

ifeq ($(CONFIG_DRM_MEDIATEK_TV_LEGACY),y)
SUB_FOLDER = mt5870
else
SUB_FOLDER = merak
endif

mediatek-drm-y := mtk_disp_color.o \
		  mtk_disp_ovl.o \
		  mtk_disp_rdma.o \
		  mtk_drm_crtc.o \
		  mtk_drm_ddp.o \
		  mtk_drm_ddp_comp.o \
		  mtk_drm_drv.o \
		  mtk_drm_fb.o \
		  mtk_drm_gem.o \
		  mtk_drm_plane.o \
		  mtk_dsi.o \
		  mtk_mipi_tx.o \
		  mtk_dpi.o

ccflags-y := -DMSOS_TYPE_LINUX_KERNEL
ccflags-y += -DSTI_PLATFORM_BRING_UP
ifdef CONFIG_DRM_MEDIATEK_TV
ccflags-y += -DMTK_TV_DRIVER
endif
ccflags-y += -DCONFIG_GOP_AFBC_FEATURE
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/gop/msos/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/gop/api/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/gop/drv/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/gop/hal/$(CONFIG_MSTAR_CHIP_NAME)/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/ldm/api/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/ldm/drv/include/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/ldm/drv/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/xc/api/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/video_display/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/video_globalpq/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/video_pnl/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/video_pixelshift/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/common/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/metabuf/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/pqmap/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/autogen/
ccflags-y += -I$(LOCAL_PATH)/MTK_TV/$(SUB_FOLDER)/pqu_metadata/
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/pqu
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/common
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/render/video_display
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/render/video_pnl
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/render/video_globalpq
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/render/video_pixelshift
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/render/common
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/render/cvbso
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/common
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/common/linux_kernel
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/xc_alg
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/scriptmgt
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/pqu
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/pqu/drivers/meta/include
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/meta_utility
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/pixelmonitor
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/pqmap_utility
ccflags-y += -I$(srctree)/drivers/iommu/mtk_iommu_dtv
ccflags-y += -I$(srctree)/drivers/soc/mediatek/mtk-memory
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/tv_cpuif/include
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/tv_cpuif
ccflags-y += -I$(KERNEL_PATH)/drivers/soc/mediatek/realtime
CONFIG_MSTAR_CHIP_NAME := $(subst ",,$(CONFIG_MSTAR_CHIP_NAME))

obj-$(CONFIG_DRM_MEDIATEK) += mediatek-drm.o

mediatek-drm-tv-objs := MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_gop_wrapper.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_kms.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_pattern.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_video.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_gop.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_ld.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_drv.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_fb.o
#mediatek-drm-tv-objs += mtk_tv_drm_fb.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_plane.o
#mediatek-drm-tv-objs += mtk_tv_drm_plane.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_crtc.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_encoder.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_connector.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_gem.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_tvdac.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/mtk_tv_drm_sync.o
#mediatek-drm-tv-objs += mtk_tv_drm_gem.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/gop/msos/sti_msos.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/gop/drv/drvGOP.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/gop/api/mapiGOP.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/gop/api/apiGOP.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/ldm/drv/drvLDM_sti.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/ldm/api/apiLDM.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_display/mtk_tv_drm_video_display.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_display/mtk_tv_drm_video_frc.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_display/mtk_tv_drm_video_frc_thermal.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_globalpq/mtk_tv_drm_pnlgamma.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_globalpq/mtk_tv_drm_pqgamma.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_globalpq/mtk_tv_drm_demura.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_globalpq/mtk_tv_drm_global_pq.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_pnl/mtk_tv_drm_panel_common.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_pnl/mtk_tv_drm_gfx_panel.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_pnl/mtk_tv_drm_extdev_panel.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_pnl/mtk_tv_drm_video_panel.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/video_pixelshift/mtk_tv_drm_video_pixelshift.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/common/mtk_tv_drm_common.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/common/mtk_tv_drm_common_irq.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/metabuf/mtk_tv_drm_metabuf.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/pqmap/mtk_tv_drm_pqmap.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/autogen/mtk_tv_drm_autogen.o
mediatek-drm-tv-objs += MTK_TV/$(SUB_FOLDER)/pqu_metadata/mtk_tv_drm_pqu_metadata.o

#ifeq ($(CONFIG_DRM_MEDIATEK_TV), m)
#mediatek-drm-tv-objs += ../drm_gem_cma_helper.o
#endif

obj-$(CONFIG_DRM_MEDIATEK_TV) += mediatek-drm-tv.o


mediatek-drm-hdmi-objs := mtk_cec.o \
			  mtk_hdmi.o \
			  mtk_hdmi_ddc.o \
			  mtk_mt8173_hdmi_phy.o

obj-$(CONFIG_DRM_MEDIATEK_HDMI) += mediatek-drm-hdmi.o
