
############################################################
# Makefile for mtk-cfm.ko
#
#
#
#
############################################################

.PHONY: clean
clean:
	rm *.o


mtk-cfm-objs += cfm.o


obj-m += mtk-cfm.o


ccflags-y += -Idrivers/media/dvb-frontends/cfm/

