##############################################################################
#MediaTek Inc. (C) 2018. All rights reserved.
#Copyright Statement:
#This software/firmware and related documentation ("MediaTek Software") are
#protected under relevant copyright laws. The information contained herein is
#confidential and proprietary to MediaTek Inc. and/or its licensors. Without
#the prior written permission of MediaTek inc. and/or its licensors, any
#reproduction, modification, use or disclosure of MediaTek Software, and
#information contained herein, in whole or in part, shall be strictly
#prohibited.
#BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
#THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
#RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
#ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
#WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
#WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
#NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
#RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
#INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
#TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
#RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
#OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
#SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
#RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
#STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
#ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
#RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
#MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
#CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#The following software/firmware and/or related documentation ("MediaTek
#Software") have been modified by MediaTek Inc. All revisions are subject to
#any receiver's applicable license agreements with MediaTek Inc.
##############################################################################
LOCAL_PATH ?= $(M)

export CONFIG_VIDEO_MEDIATEK_EARC=m

MTK_EARC_PATH=$(src)
ccflags-y := -DMSOS_TYPE_LINUX_KERNEL
ccflags-y += -DSTI_PLATFORM_BRING_UP
ccflags-y += -I$(KERNEL_PATH)/drivers/soc/mediatek/mtk-memory
ccflags-y += -Idrivers/staging/android/ion
ccflags-y += -I$(MTK_EARC_PATH)/
ccflags-y += -I$(MTK_EARC_PATH)/include/
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/common/linux_kernel

ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/common
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/earc
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/meta_utility

ccflags-y += -I$(KERNEL_PATH)/drivers/iommu/mtk_iommu_dtv
#ccflags-y += -I$(MDRV_MTKDRV_SCRIPTMGT_SRC_DIR)/include

ccflags-y += -I$(MTK_EARC_PATH)/utp/
ccflags-y += -I$(MTK_EARC_PATH)/utp/drv/earc/include
ccflags-y += -I$(MTK_EARC_PATH)/utp/drv/earc

ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/common
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg
ccflags-y += -I$(REPO_ROOT_PATH)/mtktv_drivers/ree/include/hwreg/earc

CONFIG_MSTAR_CHIP_NAME := $(subst ",,$(CONFIG_MSTAR_CHIP_NAME))

mtk-earc-objs := mtk_earc.o
mtk-earc-objs += mtk_earc_sysfs.o

mtk-earc-objs += utp/sti_msos.o
mtk-earc-objs += utp/drv/earc/drvEARC.o


#obj-$(CONFIG_VIDEO_MEDIATEK_SOURCE_CAPTURE)+= mtk-earc.o
#obj-y += mtk-earc.o
obj-m += mtk-earc.o
