# SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause)
# Makefile for MTK DVB adapter device drivers

# general options
#EXTRA_CFLAGS +=

# files
mtk-dvb-adapter-objs = mdrv_adapter.o

obj-$(CONFIG_MEDIATEK_DVB_ADAPTER) += mtk-dvb-adapter.o
