/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#define CLK_SCDISP_SCDISP_V1_ODCLK_INT_CK	1
#define CLK_SCDISP_XC_LPLL_DIV4_INT_CK	2
#define CLK_SCDISP_LD_EDGE2D_SRAM_INT_CK	3
#define CLK_SCDISP_LDCOMP_SRAM_INT_CK	4
#define CLK_SCDISP_LDMCG_SRAM_INT_CK	5
#define CLK_SCDISP_PQ_GA_SRAM_INT_CK	6
#define MT5897_SCDISP_NR	7
