##############################################################################
#MediaTek Inc. (C) 2018. All rights reserved.
#Copyright Statement:
#This software/firmware and related documentation ("MediaTek Software") are
#protected under relevant copyright laws. The information contained herein is
#confidential and proprietary to MediaTek Inc. and/or its licensors. Without
#the prior written permission of MediaTek inc. and/or its licensors, any
#reproduction, modification, use or disclosure of MediaTek Software, and
#information contained herein, in whole or in part, shall be strictly
#prohibited.
#BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
#THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
#RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
#ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
#WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
#WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
#NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
#RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
#INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
#TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
#RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
#OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
#SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
#RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
#STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
#ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
#RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
#MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
#CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#The following software/firmware and/or related documentation ("MediaTek
#Software") have been modified by MediaTek Inc. All revisions are subject to
#any receiver's applicable license agreements with MediaTek Inc.
##############################################################################

ccflags-y += -I$(srctree)/drivers/soc/mediatek/mtk-memory
ccflags-y += -I$(srctree)/drivers/clk/mediatek

ccflags-y += -Wall -Werror
cppflags-y += -Wall -Werror

obj-$(CONFIG_SND_MT5896) += mtk-mic-communication.o
mtk-mic-communication-objs += ./vbdma.o
mtk-mic-communication-objs += voc_drv_rpmsg.o
mtk-mic-communication-objs += voc_common.o

obj-$(CONFIG_SND_MT5896) += mtk-mic-capture.o
mtk-mic-capture-objs += voc_card.o
mtk-mic-capture-objs += voc_vd_task.o
mtk-mic-capture-objs += voc_communication.o
mtk-mic-capture-objs += voc_drv_paganini.o
mtk-mic-capture-objs += voc_hal_paganini.o
mtk-mic-capture-objs += voc_drv_mailbox.o
mtk-mic-capture-objs += voc_hal_mailbox.o
mtk-mic-capture-objs += voc_drv_stub.o
mtk-mic-capture-objs += voc_common.o

obj-$(CONFIG_SND_MT5896) += mtk-audio-mcu-communication.o
mtk-audio-mcu-communication-objs += audio_mcu_communication.o
mtk-audio-mcu-communication-objs += audio_mcu_rpmsg.o

obj-$(CONFIG_SND_MT5896) += mtk-audio-mcu.o
mtk-audio-mcu-objs += audio_mcu.o

obj-$(CONFIG_SND_MT5896) += mtk-aloop.o
mtk-aloop-objs += audio_loopback.o

KBUILD_EXTRA_SYMBOLS += $(MDRV_MTKDRV_METAUTIL_SRC_DIR)/Module.symvers
